// shoppingcart/src/components/link-image.jsx
import React from 'react'
import styled from 'styled-components'

const LinkImage = styled.a`
	display: inline-block;
	img{
		width: 100%;
	}
`

export default (props) => (
  <LinkImage style={props.style} href={props.href} title={props.title}>
    <img src={props.src} alt={props.alt}/>
  </LinkImage>
)

// shoppingcart/src/components/link-image.vue
<template>
    <a class="link-image" :href="href" :title="title">
        <img :alt="title" :src="src">
    </a>
</template>

<style scoped>
    .link-image{
        display: block;
    }

    .link-image img{
        display: block;
        width: 100%;
    }
</style>

<script>
    export default{
        props: [
            'href',
            'title',
            'src'
        ]
    }
</script>
