// pcme/src/components/link-image.vue
<template>
    <a :href="href" :title="title">
        <img :alt="title" :src="src">
    </a>
</template>

<script>
    export default{
        props: [
            'href',
            'title',
            'src'
        ]
    }
</script>
<style scoped>
    img{
        width: 80px;
        height: 108px;
        position: relative;
        top: 5px;
    }
    a{
        display: block;
    }
</style>

// shoppingcart/src/components/link-image.jsx
import React from 'react'
import styled from 'styled-components'

const LinkImage = styled.a`
	display: inline-block;
	img{
		width: 100%;
	}
`

export default (props) => (
  <LinkImage style={props.style} href={props.href} title={props.title}>
    <img src={props.src} alt={props.alt}/>
  </LinkImage>
)
