// geeko/src/components/product.vue
<template>
    <div class="el-list-product">
        <a :href="productUrl">
            <figure>
                <div class="img">
                    <img :src="imageUrl"/>
                </div>

                <figcaption>
                    <p class="st-ellipsis el-product-name">{{product.name}}</p>
                    <div class="st-table st-fullwidth">
                        <div class="st-cell st-v-m">
                            <span class="el-product-price">{{price}}</span>
                            <del class="el-product-del">{{delPrice}}</del>
                        </div>
                        <div class="st-cell st-v-m st-t-r">
                            <i @click.prevent="likeHandle" class="iconfont el-product-like" :class="{'red':liked}">&#xe601;</i>
                        </div>
                    </div>
                </figcaption>
            </figure>
        </a>
    </div>
</template>

<style scoped lang="scss">
    .el-list-product {

        .el-product-name{
            font-size: 12px;
        }

        a{
            text-decoration: none;
            color: #222928;
        }
        .img{
            position: relative;
            &::after{
                content: '';
                display: block;
                margin-top: 133%;
            }
            overflow: hidden;
        }

        img {
            display: block;
            position: absolute;
            width: 100%;
            top: 0;
            left: 0;
        }

        .el-product-price {
            font-size: 16px;
            font-weight: bold;
        }

        .el-product-del {
            color: #666;
            font-size: 12px;
            margin-left: 4px;
        }

        .el-product-like {
            font-size: 20px;
            &.red {
                color: #e5004f;
            }
            cursor: pointer;
        }

        figcaption {
            & > * {
                margin-top: 5px;
            }
            height: 50px;
        }
    }
</style>

<script type="text/ecmascript-6">
    import {imageutil, unitprice , producturl} from '../utils/geekoutils'
    import _ from 'lodash'

    export default{
        props: {
            product: Object,
            required: true
        },
        computed: {
            imageUrl(){
                return imageutil.getMedium(this.product.pcMainImage)
            },
            price(){
                if (this.product.promotion && this.product.promotion.enabled) {
                    return unitprice(this.product.promotion.promotionPrice)
                }
                return unitprice(this.product.price)
            },
            delPrice(){
                if (this.product.msrp && this.product.msrp.amount > 0)
                    return unitprice(this.product.msrp)
                if (this.product.promotion && this.product.promotion.enabled)
                    return unitprice(this.product.price)
                return ''
            },
            liked(){
                var wishlist = this.$store.getters['me/wishlist']
                if (wishlist && wishlist.length && wishlist[0].productIds && wishlist[0].productIds.length) {
                    return _.indexOf(wishlist[0].productIds, this.product.id) >= 0
                }

                return false
            },
            productUrl(){
                return window.ctx + '/' + producturl(this.product)
            }

        },
        methods: {
            likeHandle(){
                var wishlist = this.$store.getters['me/wishlist']
                var index = _.indexOf(wishlist[0].productIds, this.product.id)
                if (index < 0) {
                    this.$store.dispatch('like', this.product.id)
                } else {
                    this.$store.dispatch('unlike',  this.product.id)
                }
            }
        }
    }
</script>

// shoppingcart/src/components/msite/product.jsx
import React from 'react'
import styled from 'styled-components'
import {producturl, getlowerprice, gethigherprice} from '../../utils/utils.js'
import Ellipsis from '../ellipsis.jsx'
import {Grey, Red, Small} from '../text.jsx'
import Money from '../money.jsx'

const PRODUCT = styled.figure`
	.__image{
		position: relative;
		& > img{
			display: block;
			position: absolute;
			width: 100%;
			left: 0;
			top: 0;
		}
		&::after{
			margin-top: 133%;
			content:'';
			display: block;
		}

		overflow:hidden;
		background-color: #e5e5e5;
	}

	figcaption{
		& > .__name{
			margin-top: 10px;
		}

		& > .__prices{
			margin-top: 5px;
		}
	}
`

const Product = ({product}) => {
  const lower = getlowerprice(product), higher = gethigherprice(product)
  return <div>
  	<a href={producturl(product)} style={{textDecoration: 'none', color: '#222'}}>
  	  <PRODUCT>
  	  	<div className="__image">
  	  		<img src={`https://dgzfssf1la12s.cloudfront.net/medium/${product.pcMainImage}`}/>
  	  	</div>
  	  	<figcaption>
  			<Ellipsis className="__name">{product.name}</Ellipsis>
  			<div className="__prices">
  				<Money style={{fontWeight: 'bold'}} money={lower}/>
  				{higher && <del style={{marginLeft: 10}}><Grey><Small ><Money money={higher}/></Small></Grey></del>}
  			</div>
  	  	</figcaption>
      </PRODUCT>
  	</a>
  </div>
}

export default Product
