// pcme/src/components/coupon/coupon.vue
<template>
    <div class="coupon-item">
            <div class="__vm x-fw __fixed"
                :style="{background: `url(${
                    isExpired ? 
                    'https://image.geeko.ltd/chicme/20220801/expired_coupon.png': 
                    'https://image.geeko.ltd/chicme/2021-12-17/coupon_available.png'
                }) no-repeat` ,
                    'background-size': '100% 100%', 'height':'100%'}"
                >
                <div class='couponMainInfo'>
                    <div class="x-cell" style="height: 100%">
                        <div style="display: flex; align-items: center; justify-content: flex-start">
                            <span class="couponAmount" :style="{'color': `${isExpired?'#666666':'#ff782a'}`}">{{coupon.coupon.name}}</span>
                        </div>
                        
                        <div v-if="coupon.coupon.condition" :style="{ 'margin-top': 6, 'color': `${isExpired?'#666666':'#ff782a'}` }">
                            <span class='description'>{{coupon.coupon.condition}}</span>
                        </div>
                    
                        <div v-if="coupon.coupon.description" :style="{ 'margin-top': 6, 'color': `${isExpired?'#666666':'#ff782a'}` }">
                            <span class='description'>{{coupon.coupon.description}}</span>
                        </div>

                        <div v-if="coupon.coupon.infoMsg" :style="{ 'margin-top': 6, 'color': `${isExpired?'#666666':'#ff782a'}` }">
                            <span class='description'>{{coupon.coupon.infoMsg}}</span>
                        </div>
                    </div>

                    <div class="x-cell expired-cla" v-if="isExpired">
                        {{ $t("point.expired") }}
                    </div>
                </div>
                <div class='dateInfo'>
                    <li v-if="expireDate(coupon.coupon)">
                        <span class='dot'>.</span>
                        <span class="el-coupon-date">{{expireDate(coupon.coupon)}}</span>
                    </li>
                        
                    <li v-if="coupon.coupon.usageReminder">
                        <span class='dot'>.</span>
                        <span class="el-coupon-date">{{coupon.coupon.usageReminder}}</span>
                    </li>
                </div>
            </div>
        </div>
</template>

<script>
    import fecha from 'fecha'

    export default {
        name:"Coupon",
        props:{
            coupon:{
                type:Object,
                required:true
            },
            isExpired:{
                type:Boolean,
                default:false
            }
        },
        mounted(){
        },
        methods:{
            expireDate(item){
                var [beginDate, endDate] = [item.beginDate, item.endDate]


                if (beginDate && endDate) {
                    return fecha.format(beginDate,"DD/MM/YYYY HH:mm") + "~" + fecha.format(endDate,"DD/MM/YYYY HH:mm");
                }

                return ''

            }
        }
    }
</script>

<style scoped lang="scss">
    .coupon-item{
        width: 435px;
        height: 177px;
        // border: solid 1px #e6e6e6;
        float: left;
        margin-bottom: 20px;
        position: relative;
        .fl-l{
            width: 69%;
            float: left;
            padding-top: 20px;
            padding-left: 20px;
            i{
                position: absolute;
                right: 140px;
                bottom: 0px;
                font-size: 80px;
                color: #e6e6e6;
            }
        }
        .fl-r{
            float: right;
            background-color: #f46e6d;
            width: 31%;
            height: 100%;
            background: radial-gradient(transparent 0, transparent 4px, #f46e6d 4px);
            background-size: 15px 14px;
            background-position: 8px 0px;
            padding-left: 5px;
            .bg{
                width: 100%;
                height: 100%;
                padding: 48px 20px;
                background-color: #f46e6d;
                .usenow{
                    border: 1px solid #ffffff;
                    border-radius: 20px;
                    color: white;
                    text-align: center;
                    cursor: pointer;
                    line-height: 26px;
                }
                .unabled{
                    color: rgba(255,255,255,.5);
                    border: 1px solid rgba(255,255,255,.5);
                    cursor: not-allowed;
                }
            }
        }
        &:nth-child(n){
            margin-right: 20px;
        }
        .amount{
            color: #E64545;
            font-size: 28px;
            line-height: 30px;
            font-weight: bold;
            span{
                font-size: 18px;
                font-weight: normal;
            }
        }
        .name{
            font-size: 16px;
            color: #222;
            margin: 6px 0;
        }
        .time{
            font-size: 14px;
            color: #666;
        }
    }


    .couponAmount{
        font-weight: normal;
        font-stretch: normal;
        letter-spacing: 0px;
        margin-right: 10px;
        white-space: nowrap;
        font-family: 'ACUMINPRO-BOLD';
        font-size: 26px;
        line-height: 31px;
        text-transform: uppercase;
    }

    .couponMainInfo{
        display: flex;
        align-items: flex-start;
        justify-content: space-between;
        height: 120px;
        border-bottom: 1px solid #fff;
        padding: 16px 20px 8px 20px;

        & > div.expired-cla{
            text-align: center;
            position:relative;
            background: #BBBBBB;
            padding: 5px 29px;
            color: #444444;
        }
    }
    .dateInfo{
        padding: 4px 20px;
        font-family: 'SLATEPRO';
        font-size: 14px;
        font-weight: normal;
        font-stretch: normal;
        letter-spacing: 0px;
        color: #999999;

        & > li{
            position: relative;
            top: -2px;
        }
    }

    .description{
        overflow: hidden;
        display: -webkit-box;
        -webkit-box-orient: vertical;
        -webkit-line-clamp: 1;
        line-height: 20px;
        font-size: 16px;
    }
    
    .dot{
        vertical-align: super;
        position: relative;
        top: 2px;
    }
</style>

// shoppingcart/src/components/pc/coupon.jsx
import React from 'react'
import styled from 'styled-components'
import {injectIntl} from 'react-intl'

const UseNow = styled.div`
	width: 81px;
	height: 26px;
	border-radius: 100px;
	border: solid 1px #ffffff;
	text-align: center;
	line-height: 24px;
	color: #fff;
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);
	cursor: pointer;
	font-size: 12px;
`

const StyledCoupon = styled.div`
	width: 330px;
	height: 92px;
	border: solid 1px #e6e6e6;

	.__content{
		width: 226px;
		padding-left: 15px;
	}

	.__background{
		width: 104px;
		background: radial-gradient(transparent 0, transparent 5px, #F46E6D 5px);
		background-size: 15px 15px;
		background-position: 7px 3px;
		height: 92px;
		position: relative;

		&::before {
	    content: '';
	    position: absolute;
	    background-color: #F46E6D;
	    top: 0;
	    bottom: 0;
	    left: 7px;
    	right: 0px;
		}


		&.__disabled{
			background: radial-gradient(transparent 0, transparent 5px, #cacaca 5px);
			&::before{
				background-color: #cacaca;
			}
		}
	}



	.__title{
		font-size: 20px;
		text-transform: uppercase;
		color: #e64545;
		font-family: HelveticaNeue-Bold;
	}

	.__description{
		font-size: 14px;
		color: #222;
		margin-top: 2px;
	}

	.__expire{
		font-size: 12px;
		color: #666;
		margin-top: 12px;
	}

	.__usenow{
		&:acitve{
			background-color: #F46E6D;
		}
	}

	&.__disabled{
		.__background{
			background: radial-gradient(transparent 0, transparent 5px, #cacaca 5px);
			background-size: 15px 15px;
    	background-position: 7px 3px;
			&::before{
				background-color: #cacaca;
			}
		}

		.__title{
			color: #999999;
		}

		.__description{
			color: #999;
		}

		.__usenow{
			cursor: default;
			opacity: .8;
			&:acitve{
				background-color: #cacaca;
			}
		}
	}

	&.__selected{
		border: solid 1px #F46E6D;
		.__background{
			background: radial-gradient(transparent 0, transparent 5px, #F46E6D 5px);
			&::before {
		    background-color: #F46E6D;
			}
		}
		
	}
`

const getAmount = amount => amount ? (amount.indexOf('%') > 0 ? `${amount} off` : `$${amount}`) : ''

const TimeRange = (props) => {
  const {begin, end} = props
  return <span style={{fontSize: 12}}>
    <time>{new Date(begin).toLocaleDateString()}</time>
    <span> - </span>
    <time>{new Date(end).toLocaleDateString()}</time>
  </span>
}

const _coupon = ({intl, couponVO, couponSelect, selectedCoupon, selectedCoupon2}) => {
  const {coupon, isAvailable} = couponVO
  const selected = (selectedCoupon && coupon.id === selectedCoupon.id) || (selectedCoupon2 && coupon.id === selectedCoupon2.id)

  const selectedText = selected ? intl.formatMessage({id: 'selected'}) : intl.formatMessage({id: 'use_now'})

  return <StyledCoupon className={`x-table __vm __fixed ${!isAvailable ? '__disabled' : ''} ${selected ? '__selected' : ''}`}>
  	<div className="x-cell __content">
  		<div className="__title">
  			{coupon.couponName2}
  		</div>

  		<div className="__description">
  			{coupon.name}
  		</div>

  		<div className="__expire">
  			{coupon.beginDate && coupon.endDate && <TimeRange begin={coupon.beginDate} end={coupon.endDate}/>}
  		</div>

  	</div>
  	<div className={`x-cell __background`}>
  		<UseNow onClick={ () => { isAvailable && couponSelect(coupon.id) } } className="__usenow">{ selectedText }</UseNow>
  	</div>
  </StyledCoupon>
}

export const Coupon = injectIntl(_coupon)

const StyledCoupons = styled.ul`
	& > li{
		margin-top: 15px;
		&:first-child{
			margin-top: 0;
		}
		
	}
`

const _coupons = ({couponVOs, selectedCoupon, couponSelect, selectedCoupon2}) => {
  return <StyledCoupons>
	  {couponVOs && couponVOs.map((vo, index) => <li key={ index }><Coupon selectedCoupon={selectedCoupon} selectedCoupon2={selectedCoupon2} couponSelect={couponSelect} couponVO={vo}/></li>)}
  </StyledCoupons>
}

export default _coupons
