// pcme/src/components/index/product.vue
<template>
    <div class="product">
        <div class="_image">
            <a :href="getProUrl(product)">
                <img :src="imageUrl(product.pcMainImage)" alt="MainIMage">
            </a>
        </div>
        <div class="p-info-price">
            <span class="f-red">{{price(product)}}</span>
            <del class="f-gray">{{delPrice(product)}}</del>
        </div>
    </div>
</template>

<script>
    import * as utils from "../../utils/geekoutil.js"

    export default {
        name:"Product",
        props:{
            product:{
                type:Object
            }
        },
        methods:{
            getProUrl(product){
                return window.ctx + '/' + utils.producturl(product)
            },
            imageUrl(imgurl){
                return utils.imageutil.getMedium(imgurl)
            },
            price(product){
                if (product.promotion && product.promotion.enabled) {
                    return utils.unitPrice(product.promotion.promotionPrice)
                }
                return utils.unitPrice(product.price)
            },
            delPrice(product){
                if (product.msrp && product.msrp.amount > 0)
                    return utils.unitPrice(product.msrp)
                if (product.promotion && product.promotion.enabled)
                    return utils.unitPrice(product.price)
                return ''
            }
        }
    }
</script>

<style scoped lang="scss">
    .product{
        ._image{
            a{
                position: relative;
                overflow: hidden;
                display: block;
                background-color: #f1f1f1;
                img{
                    display: block;
                    width: 100%;
                    height: 100%;
                    position: absolute;
                    top: 0;
                    left: 0;
                }

                &::after{
                    content: '';
                    display: block;
                    margin-top: 125%;
                }
            }
        }

        .p-info-price{
            margin-top: 5px;
            .f-red{
                font-family: 'SlatePro-Medium';
                font-size: 14px;
                color: #000000;
            }

            .f-gray{
                font-size: 12px;
                color: #999999;
            }
        }
    }
</style>

// shoppingcart/src/components/pc/product.jsx
import React from 'react'
import styled from 'styled-components'
import {producturl, getlowerprice, gethigherprice} from '../../utils/utils.js'
import {Grey, Red, Small} from '../text.jsx'
import Money from '../money.jsx'

const PRODUCT = styled.figure`
	.__image{
		position: relative;
		& > img{
			display: block;
			position: absolute;
			width: 100%;
			left: 0;
			top: 0;
		}
		&::after{
			margin-top: 125%;
			content:'';
			display: block;
		}
		

		overflow:hidden;
		background-color: #e5e5e5;
	}

	figcaption{
		& > .__prices{
			margin-top: 5px;
		}
	}
`

export default ({product}) => {
	const lower = getlowerprice(product), higher = gethigherprice(product)
	return <PRODUCT>
  	<a href={producturl(product)} style={{textDecoration: 'none', color: '#222'}}>
	    <div className="__image">
	  		<img src={`https://dgzfssf1la12s.cloudfront.net/medium/${product.pcMainImage}`}/>
	  	</div>
	  	<figcaption>
	  		<div className="__prices">
	        <Red><Money style={{fontWeight: 'bold', fontSize: 16}} money={lower}/></Red>
	        {higher && <del style={{marginLeft: 10}}><Grey><Small ><Money money={higher}/></Small></Grey></del>}
				</div>
			</figcaption>
		</a>
	</PRODUCT>
}
