// shoppingcart/src/components/msite/countdowns.jsx
import React from 'react'
import styled from 'styled-components'

const __dayoffset = 1000 * 60 * 60 * 24, __houroffset = 1000 * 60 * 60, __minuteoffset = 1000 * 60
const getFullNumber = (number) => number >= 10 ? number : ('0' + number)

export const CountDown = class extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      lefting: 0
    }
  }

  getStructeDate (lefting) {
    const day = Math.floor(lefting / __dayoffset)
    const _leftday = lefting % __dayoffset
    const hour = Math.floor(_leftday / __houroffset)
    const _lefthour = lefting % __houroffset
    const minute = Math.floor(_lefthour / __minuteoffset)
    const second = Math.floor((lefting % __minuteoffset) / 1000)

    return {
      day: getFullNumber(day),
      hour: getFullNumber(hour),
      minute: getFullNumber(minute),
      second: getFullNumber(second)
    }
  }

  componentDidMount () {
    const { offset } = this.props
    this.setState({
      lefting: offset
    })
    this.timerID = setInterval(() => {
      if (this.state.lefting - 1000 < 0) {
        clearInterval(this.timerID)
      } else {
        this.setState({
          lefting: this.state.lefting - 1000
        })
      }
    }, 1000)
  }

  componentWillUnMount () {
    clearInterval(this.timerID)
  }

  render () {
    const {day, hour, minute, second} = this.getStructeDate(this.state.lefting)
    const {showDay, showHour} = this.props
    return <span {...this.props}>
      {showDay && <React.Fragment><span>{day}</span><span>:</span></React.Fragment>}
      {showHour && <React.Fragment><span>{hour}</span><span>:</span></React.Fragment>}
      <span>{minute}</span><span>:</span>
      <span>{second}</span>
    </span>
  }
}

const StyledCountDown = styled.span`
  & > span{
      &>span{
        background-color: #222;
        width: 30px;
        height: 30px;
        text-align: center;
        color: #fff;
        border-radius: 2px;
        display: inline-block;
        line-height: 30px;
        font-size: 16px;
      }
      &>i{
        font-size:18px;
        color: #222;
        font-style: normal;
      }
  } 
`

export const CountDownBlock = (props) => <StyledCountDown>
  <CountDown {...props}/>
</StyledCountDown>

// pcme/src/components/countdowns.vue
<template>
    <div class="countdown" v-if="lefting > 0">
        <slot class="label" :style="labelStyle"></slot>
        <template v-if="showDay">
          <span :style="timeStyle">{{countdowning.day}}</span><span>:</span>
        </template>
        <template v-if="showHour">
          <span :style="timeStyle">{{countdowning.hour}}</span><span>:</span>
        </template>
        
        <span :style="timeStyle">{{countdowning.minute}}</span><span>:</span>
        <span :style="timeStyle">{{countdowning.second}}</span>
    </div>
</template>

<script>
  const __dayoffset = 1000*60*60*24, __houroffset = 1000*60*60, __minuteoffset = 1000*60;


  export default {
    name: 'countdowns',
    // 'timeLeft', 'labelStyle', 'timeStyle'
    props: {
      timeLeft:{
        type:[String,Number]
      },
      timeStyle:{
        type:Object
      },
      showDay:{
        type:Boolean,
        default:false
      },
      showHour:{
        type:Boolean,
        default:false
      }
    },
    data(){
      return {
        lefting: 0,
        timerId: null
      }
    },
    computed: {
      countdowning(){
        const lefting = this.lefting;
        const day = Math.floor(lefting / __dayoffset);
        const _leftday = lefting % __dayoffset;
        let hour = Math.floor(_leftday / __houroffset);
        const _lefthour = lefting % __houroffset;
        const minute = Math.floor(_lefthour / __minuteoffset);
        const second = Math.floor((lefting % __minuteoffset)/1000);
        // return `${this.getFullNumber(day)}:${this.getFullNumber(hour)}:${this.getFullNumber(minute)}:${this.getFullNumber(second)}`;

        if(!this.showDay){
          hour = hour + (day*24);
        }

        return {
          day: this.getFullNumber(day),
          hour: this.getFullNumber(hour),
          minute: this.getFullNumber(minute),
          second: this.getFullNumber(second)
        }
      }
    },
    methods: {
      getFullNumber(number){
        return number >= 10 ? number : ('0'+number);
      }
    },
    created(){
      let offset = 0;
      this.timerId = setInterval(() => {
        this.lefting = this.timeLeft - offset;
        offset+=1000;

        if(this.lefting <= 0){
          clearInterval(this.timerId)
        }

      }, 1000);
    },
    destroyed(){
        clearInterval(this.timerId)
    }

  };
</script>

<style scoped lang="scss">
    .countdown{
        display: inline-block;

        // .time::before{
        //     content: '\e655';
        //     font-size: 14px;
        //     margin-right: 5px;
        //     font-family: iconfont;
        // }
    }


</style>
